version: '3.9'

services:
  front:
    build: .
    container_name: ipcam_front
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8502:8501"
    restart: always

  recording:
    build: .
    container_name: ipcam_recording
    command: python record.py
    restart: always

  uploading:
    build: .
    container_name: ipcam_uploading
    command: python upload.py
