version: '3.9'

services:
  front:
    build: .
    image: ipcam-app
    container_name: ipcam_front
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8502:8501"
    restart: always
    volumes:
      - shared-data:/app/shared
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  recording:
    image: ipcam-app
    container_name: ipcam_recording
    command: python record.py
    restart: always
    volumes:
      - shared-data:/app/shared
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  cleaning:
    image: ipcam-app
    container_name: ipcam_cleaning
    command: python cleanup.py
    volumes:
      - shared-data:/app/shared
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro


volumes:
  shared-data: