version: '3.9'

services:
  front:
    build: .
    image: ipcam-app
    container_name: ipcam_front
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8502:8501"
    restart: always
    environment:
      - GDRIVE_BASE_FOLDER_ID=
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  orchestrator:
    image: ipcam-app
    container_name: ipcam-app-orchestrator
    command: python orchestrator.py
    restart: always
    environment:
      - GDRIVE_BASE_FOLDER_ID=
      - LOG_LEVEL=INFO
      - PYTHONUNBUFFERED=1
      - DOCKER_ENV=True
    volumes:
      - .:/app/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
